### ISSUE TITLE
Run full test suite in CI

### ISSUE THREAD

**Issue by Spartee** [CrayLabs/SmartRedis#143]
# Description
Currently the only CI check we do is for compilation of the 4 clients and wheel building for the Python library. Obviously this is sub-par. Now that we have unit tests and integration tests, we should be executing both whenever a contributor pushes or creates a PR. 

# Justification
Better CI coverage is necessary to help include outside contributors with their contributions and be sure that their code works with the existing implementations on different systems and versions of Python.

# Implementation Strategy
I think the best way to implement this is to take the RedisAI container on dockerhub and build in SmartRedis. Redis + RedisAI will already be built and will be started in the background. 

some steps I have working locally:
- ``docker run -p 6379:6379 -it --rm redislabs/redisai:edge-cpu &``
- ``export SSDB=<docker address:6379``
- ``export SMARTREDIS_TEST_CLUSTER=False``
- ``cd smartredis && make test``

This tests:
- All SR clients
- SR clients for CPU
- SR clients for non-cluster
- SR client unit tests in C++

This doesn't test or do:
- our coverage for Python (pytest-cov) or C++ (catch)
- SR clients for cluster
- SR clients for GPU

Obviously this doesn't spin up a cluster so we are not testing those methods, but it's better than what we have now, which is nothing. A separate ticket should be created for executing the coverage for Python and C++.

I think the steps above can be run inside a GitHub Action. At very least, a script can be created with these methods.

Open questions:
- Can we run docker steps inside a docker container?
- If not above, do we just build SmartSim and run the tests using SmartSim's local launcher?

this ticket will involve a fair amount of investigative work on the docker/github actions side of things.

**Comment by ashao** [comment]
If no one's grinding on I can probably take this on since I've done similar things in the past. At the very least, I have high confidence that I could get to the point that @Spartee did manually. I should have enough of my Github minutes, but I'll ping you for developer access to this repo if I run somehow run out.
