### ISSUE TITLE
Implement poll_dataset()

### ISSUE THREAD

**Issue by mellis13** [CrayLabs/SmartRedis#152]
# Description

Currently users are directed by documentation to use ``poll_tensor()`` to look for the existence of a dataset.  This is not intuitive, and the absence of a ``poll_dataset()`` function leaves users using ``poll_key()``.   

# Justification

If users are using ``poll_key``, it makes it hard to change the backend representation of a dataset without breaking their code.  As a result, it makes sense to have a ``poll_dataset()`` function.

# Implementation Strategy

Implement ``poll_dataset()`` in the same way as the other poll functions.

**Comment by billschereriii** [comment]
Implementation complete but depends on error handling PR, so it's showing up as tons of updated files even though it's only 14. PR #174

**Comment by mellis13** [comment]
Let's create an issue to update SmartSim zoo examples to use poll_dataset() (https://github.com/CrayLabs/SmartSim-Zoo)
