### ISSUE TITLE
Update Redis++ dependency to 1.3.2

### ISSUE THREAD

**Issue by mellis13** [CrayLabs/SmartRedis#153]
# Description
The Redis++ 1.3.2 release includes a PR that was submitted to enable a default constructor with ``QueuedReplies``.  This should unblock #79 .

# Justification
Updating to Redis++ 1.3.2 should allow work to continue on pipelining dataset and client commands.

# Implementation Strategy
Upgrade to 1.3.2 and then continue work on #79 .

**Comment by billschereriii** [comment]
@mellis13 this can be closed, right?
