### ISSUE TITLE
Need to document compilers we've built with

### ISSUE THREAD

**Issue by billschereriii** [CrayLabs/SmartRedis#154]
Especially now that we'll be compiling with -Wall, we need to document the compilers we know we work so if someone tries another compiler and hits a snag they can let us know.

Acceptance criteria:

- [ ] Add documentation on which compilers are tested on daily basis (gnu/intel/clang)
- [ ] Add docs for compiles that are not tested but have been used (e.g. cray, nvhpc, pgi)

**Comment by Spartee** [comment]
@billschereriii has there been progress on this?
