### ISSUE TITLE
Many cases where objects are returned by value

### ISSUE THREAD

**Issue by billschereriii** [CrayLabs/SmartRedis#157]
Returning objects by value in C++ (as opposed to return by reference or by pointer) causes the` C++ runtime to make a copy of the object for the call site. This is generally just a performance issue, but can expose problems if copy constructors are not set up correctly.

Need to go through the code and rework class interfaces to eliminate this usage, though the performance degradation from this is usually relatively minor.

**Comment by Spartee** [comment]
@billschereriii is this still the case after the error handling PR? Whats the priority here? tagging @mellis13 too for visibility.

**Comment by billschereriii** [comment]
I'll have to go back and review. I did not specifically address this as part of the error handling PR as it was getting excessively big as it was.

**Comment by billschereriii** [comment]
With move constructors, the impact of this is minimal. No need for changes.
