### ISSUE TITLE
Spike: Logger for client activity

### ISSUE THREAD

**Issue by mellis13** [CrayLabs/SmartRedis#171]
# Description
PR #159 addresses the need for better error handling across all languages, but SmartRedis users and developers would also benefit from a log of SmartRedis actions and the ability to adjust the verbosity of the logs.

# Justification
With SmartRedis being used in different environments and with different hardware, detailed logs would help users and developers understand the sequence of events affecting performance or causing errors.

# Implementation Strategy
There are many ways this could be implemented, but it should be compatible across all client languages.

# Acceptance

- [ ] Develop requirements for the logger
- [ ] Develop design for the logger with example code.  Present design to group for feedback.
- [ ] Make follow-up tickets for logger implementation in each languages.

**Comment by ashao** [comment]
One area where the logging is going to be a benefit for devs is to understand the mapping from keys provided by the user to the actual key that's stored in the database. I can very easily see scenarios where someone is expecting that an aggregation is being done on an ensemble, but the user was expecting it for a single member.
