### ISSUE TITLE
Select CPU or GPU for compiled client tests

### ISSUE THREAD

**Issue by mellis13** [CrayLabs/SmartRedis#20]
**Description**
Currently, the compiled client tests have ``CPU`` specified in the source file.  It might be worthwhile to specify CPU or GPU via the ``setup_test_env.sh`` file or some other mechanism so the user or developer can switch between ``CPU`` and ``GPU``.

**Comment by ashao** [comment]
Closed by https://github.com/CrayLabs/SmartRedis/pull/254
