### ISSUE TITLE
Support for GNU compiler and Fortran

### ISSUE THREAD

**Issue by cbegeman** [CrayLabs/SmartRedis#216]
# Description
Currently, the C-style enum declared in [enum_fortran.inc](https://github.com/CrayLabs/SmartRedis/blob/develop/include/enum_fortran.inc) for C-Fortran interoperability cannot have a universal kind when compiling Fortran code with GNU. (This issue arose for me with GNU 6.4.0.)

# Justification
Support for more compilers.

# Implementation Strategy
We resolved this issue by replacing
```
enum, bind(c)
  enumerator :: dummy = 0
end enum
integer, parameter :: enum_kind = kind(dummy)
```
with
```
integer, parameter :: enum_kind = 4

**Comment by cbegeman** [comment]
@ashao Per our discussion, I've documented the issue for a rainy day.

**Comment by ashao** [comment]
Thank you @cbegeman! I'll ping you in a couple of weeks to make sure that the fix I have in mind fixes your problem.
