### ISSUE TITLE
SR DataSet Conversions

### ISSUE THREAD

**Issue by Spartee** [CrayLabs/SmartRedis#224]
# Description

In order to make SmartRedis ``DataSet`` objects more amenable to activies like online analysis and training, we should investigate data formats that make sense to be able to convert to and from.

Additionally, this epic will also track the effort necessary to do aggregations for when global domains are needed before converting datasets.

## To investigate

 - [xarray](https://docs.xarray.dev/en/stable/)
 - [Zarr](https://github.com/zarr-developers/zarr-python)
 - [conduit](https://github.com/LLNL/conduit)
 - [feather](https://arrow.apache.org/docs/python/feather.html)
 - [Parquet](https://arrow.apache.org/docs/python/parquet.html)
 - [HDF5](https://docs.h5py.org/en/stable/)

the goal is to have a ``to_<file format>`` and ``from_<file_format>`` method for each of the types we end up choosing.

If you would like to see others, please let us know.

**Comment by ashao** [comment]
https://zarr.readthedocs.io/en/stable/index.html should definitely be on there a well.

**Comment by ashao** [comment]
Woops you ninja-edited that in there.

**Comment by mellis13** [comment]
Closing this epic as the scope and strategy is likely much different than this was created in Feb 2022.
