### ISSUE TITLE
Client.DataSet.to_xarray

### ISSUE THREAD

**Issue by Spartee** [CrayLabs/SmartRedis#226]
# Description
[Xarray](https://docs.xarray.dev/en/stable/) is a widely used data format in the scientific community. Xarray provides an interface to file formats like netcdf that can be read into memory and supplied with a whole host of useful functions.

Examples: https://docs.xarray.dev/en/stable/gallery.html

*Xarray description from [documentation](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.html#xarray.Dataset)*
- A multi-dimensional, in memory, array database.
- A dataset resembles an in-memory representation of a NetCDF file, and consists of variables, coordinates and attributes which together form a self describing dataset.
- Dataset implements the mapping interface with keys given by variable names and values given by DataArray objects for each variable name.
- One dimensional variables with name equal to their dimension are index coordinates used for label based indexing.

# Justification
A number of SmartSim users currently use Xarray as well. Providing a method to convert a SmartRedis ``DataSet`` to an Xarray object would provide SmartRedis users with immediate plotting, manipulation, and other functionality.

# Implementation Strategy

Before this ticket is started, #225 should be completed as it has a major impact on how this feature will be designed.

Sample interface
```python
class DataSet:

    def to_xarray(self, coords=None, attrs=None): -> xarray.Dataset

```

Open Design questions:
- Optionally transmit coordinates through ``DataSet`` metadata?
- tensor keys used for data variable names?
- Are we able to make this a zero-copy converstion? Assuming yes b/c of numpy memoryviews.

**Comment by mellis13** [comment]
closing as duplicate
