### ISSUE TITLE
Make test suite dependent on redis server connection

### ISSUE THREAD

**Issue by ben-albrecht** [CrayLabs/SmartRedis#236]
# Description
Make test suite dependent on redis server connection, such that testing fails early if a client is not able to find and connect to a redis server, rather than running the full test suite.

# Justification
This feature will save time / improve clarity for developers who run the test suite and may have their redis server configured incorrectly.

# Implementation Strategy
A simple way to implement this would be to run a minimal connection test prior to running the full test suite. @billschereriii pointed out that we should still build the non-python tests before running this check, to report build errors back to users even if the redis server connection fails.

**Comment by billschereriii** [comment]
This was effectively implemented as part of the test/build system rework.
