### ISSUE TITLE
Documentation for Fortran interface misses definitions for some parameters

### ISSUE THREAD

**Issue by billschereriii** [CrayLabs/SmartRedis#255]
# Description
The Doxygen compiler is not able to trace into Fortran include files, so in the cases where we've built macros for the bodies of functions specialized to the different datatypes (such as put_tensor), the documentation that's embedded within the include file is not read or processed and thus doesn't make it to the final documentation.

Note: I (Bill) attempted to use the techniques described in this [article](https://stackoverflow.com/questions/62592165/doxygen-fails-to-process-header-files-in-fortran-code) to get around the problem, but was not successful. As a result, the only way I know to resolve this would be to move the full function header to the main client.f90 or dataset.f90 file.

# How to reproduce
Run `make docks` to build documentation and then open the resulting docs. Documentation defined in include files for parameters of Fortran SmartRedis interface methods is missing.

# Expected behavior
All documentation should make its way to the user docs

# System
 - OS: all
 - OS version: all
 - Commit/version of library: all

**Comment by ashao** [comment]
I futzed around with some of the Doxygen parameters and nothing seemed to quite work. I'd suggest going with option B. Add a `cpp` preprocessing step to the `Makefile` for the documentation to create `dataset.F90` and `client.F90` in a temporary directory and update the `Doxyfile_fortran` to point to that folder instead.
