### ISSUE TITLE
Import Xarray in SmartRedis

### ISSUE THREAD

**Issue by juliaputko** [CrayLabs/SmartRedis#273]
# Description
A strategy is needed to come up with how to import Xarray in SmartRedis to use the Dataset Conversion methods. 

# Justification
SmartRedis users that would like to use the Dataset Conversion methods for Xarray and other format types will need to install packages for the conversion to those data formats. 

# Implementation Strategy
- Should not force users to install Xarray and all other datatype dependencies just to use SmartRedis. 
- Could look at make test_deps 
- Could have different extras for the package

**Comment by mellis13** [comment]
This has been completed.
