### ISSUE TITLE
Smart Redis Test Suite is Incompatible with Python 3.10

### ISSUE THREAD

**Issue by MattToast** [CrayLabs/SmartRedis#319]
## Description
Currently, everything all code written in the SR python layer should be compatible with python 3.10. Given that and the fact SmartSim now has support for python 3.10 we should consider testing SR against python 3.10 in our CI.

Unfortunately, the SR test suite has a dependency on `pytorch==1.7.1` which does not have a wheel available for python 3.10. This means we cannot run the test suite using python 3.10

## How to reproduce
Attempt to install `smartredis` with python 3.10 with the optional dev deps (`pip install smartredis[dev]`). You should recieve an error to the affect of:
```
ERROR: Could not find a version that satisfies the requirement torch==1.7.1; extra == "dev" (from smartredis[dev,xarray]) (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0)
ERROR: No matching distribution found for torch==1.7.1; extra == "dev"
```

## Expected behavior
I should be able to run `pip install smartredis[dev]` and `make test` with python 3.10 and not get a dependency-not-supported error

## System
 - OS: MacOS (applies to all)
 - OS version: NA
 - Python version: 3.10
 - Commit/version of library: [6729a59](https://github.com/CrayLabs/SmartRedis/commit/6729a59b9abd1730810c5d8db46ebd1229c8aa5b)

**Comment by billschereriii** [comment]
Will be incorporated into the build/test redesign
