### ISSUE TITLE
`initialize` should be a SUBROUTINE error

### ISSUE THREAD

**Issue by b-fg** [CrayLabs/SmartRedis#335]
I am using v0.4.0 and the following MWE
```fortran
module mod_smartredis
   use smartredis_client, only: client_type
   implicit none

   type(client_type) :: client

   contains

   subroutine init_smartredis(client)
      type(client_type), intent(inout) :: client
      call client%initialize(.false.)
   end subroutine init_smartredis
end module mod_smartredis
```
errors during compilation in
```
    |          call client%initialize(.false.)
    |                                        1
Error: ‘initialize’ at (1) should be a SUBROUTINE
```

Is there something wrong in the MWE? I believe I am correctly compiling and linking the library since the use `smartredis_client, only: client_type` import works as intended. Any help would be appreciated, thanks!

**Comment by ashao** [comment]
Thanks for catching that. I'm assuming that you found that part of it by following this part of the documentation? https://www.craylabs.org/docs/sr_integration.html

If so, that example is not up-to-date as it precedes when we changed the interfaces to returning error codes. As such, almost all the methods associated with `Dataset` and `Client` are now functions instead of subroutines

For your implementation you should be able to change this to 

```
module mod_smartredis
   use smartredis_client, only: client_type
   implicit none

   type(client_type) :: client

   contains

   subroutine init_smartredis(client)
      type(client_type), intent(inout) :: client
      integer :: return_code
      return_code = client%initialize(.false.)
   end subroutine init_smartredis
end module mod_smartredis
```

**Comment by b-fg** [comment]
Oh, yes it has changed I see... I actually followed the section "Initializing the SmartRedis client" of the [Fortan documentation](https://www.craylabs.org/docs/sr_fortran_walkthrough.html), which seems that it also needs to be updated. Changing to a function call works as expected. And thanks for the prompt response :)

**Comment by ashao** [comment]
Not a problem. I'll close this issue once we merge in the documentation update. I added a little section about error handling in Fortran as well if you're interested in that: 
https://github.com/CrayLabs/SmartSim/pull/284/files

Thanks again for pointing this out to us!

**Comment by b-fg** [comment]
That's great, thanks for the work!
