### ISSUE TITLE
Fortran `poll_tensor` logical type of `exists`

### ISSUE THREAD

**Issue by b-fg** [CrayLabs/SmartRedis#337]
The `poll_tensor` implementation for Fortran requires a `logical(kind=c_bool)` type for the `exists` flag. Why is that? Wouldn't a normal `logical` work? Or, otherwise, couldn't this be converted within the function? It seems a bit confusing that users have to use `iso_c_binding` on their side. Also the [Fortran API docs](https://www.craylabs.org/docs/api/smartredis_api.html#f/smartredis_client/poll_tensor) does not mention it.

**Comment by b-fg** [comment]
Unfortunately it is causing a fatal error during compilation using gcc 9.4.0
> Error: Type mismatch in argument ‘exists’ at (1); passed LOGICAL(4) to LOGICAL(1)

**Comment by ashao** [comment]
Interesting ... ok, yes we'll fix this. Thanks for bringing this to our attention
