### ISSUE TITLE
Linking against a static client library fails

### ISSUE THREAD

**Issue by ashao** [CrayLabs/SmartRedis#385]
# Description
Linking a Fortran application against the static version of the Fortran client library fails due to missing symbols that should be brought in via the C/C++ SmartRedis static library. As such, only linking C/C++ applications statically is currently supported. This bug likely arises due to our CMake recipes which do not embed the C/C++ libraries nor provide the necessary metadata for the linker to correctly find the symbols

# How to reproduce
From the SmartRedis 0.5.0 release, this behavior can be replicated with 

```
make build-test-fortran SR_LINK=Static
```

This will output errors like
```
[100%] Linking Fortran executable client_test_dataset
/usr/bin/ld: /home/users/shao/tmp/release/SmartRedis/install/lib/libsmartredis-fortran.a(client.F90.o): in function `__smartredis_client_MOD_get_datasets_from_list_range':
client.F90:(.text+0x1c9): undefined reference to `_get_dataset_list_range_allocated'
/usr/bin/ld: /home/users/shao/tmp/release/SmartRedis/install/lib/libsmartredis-fortran.a(client.F90.o): in function `__smartredis_client_MOD_get_datasets_from_list':
```

# Expected behavior
Linking Fortran applications statically against a static build of the Fortran interfaces should be successful

# System
 - OS: Linux/Mac
 - Commit/version of library: 0.5.0

**Comment by mellis13** [comment]
@billschereriii Add implementation options and reasoning for our final choice.

**Comment by billschereriii** [comment]
This issue is not restricted to Fortran. All clients are failing when linked statically

**Comment by billschereriii** [comment]
We have a solution that works for Linux -- combining the various dependent static libraries into a "thin library" and linking against that. Apparently, though, MacOS is a bit of a special flower, and the linkers on MacOS aren't willing to recurse into a thin library when they perform linking.

The need for static linkage is primarily on supers, so the approach we will take on this ticket is to use the thin library approach and then explicitly disable static linkage builds on MacOS.

**Comment by billschereriii** [comment]
In order to get CMake to stop linking to a shared library when we ask for a static library, we are now appending `-static` to the name of generated static libraries. So `libsmartredis-static.a`, `libsmartredis-debug-static.a`, `libsmartredis-fortran-debug-static.a`, etc.

**Comment by billschereriii** [comment]
We have discovered that CMake doesn't consider static vs shared linkage to be enough of a difference when doing configuration to merit repeat of the configuration step. This causes static and shared linkage to get muddled together chaotically for our unit tests and examples. To keep this from being a problem going forward, we are splitting out `Static` and `Shared` subdirectories under `tests` and `examples` within each `build/{build-type}`
