### ISSUE TITLE
DockerFile

### ISSUE THREAD

**Issue by Spartee** [CrayLabs/SmartRedis#42]
# Description
SmartRedis should have a base Dockerfile that users can look at and use as a template for including with their containerized jobs.

# Justification
Any user wanting to run a containerized workload with SmartRedis will be able to use the Dockerfile to build an image and include that image in their container.

# Implementation Strategy
Write a DockerFile for SmartRedis that
 - Installs dependencies
 - builds the static lib into ``/usr/local/lib``
 - build the python client and installs it into python environment.

**Comment by gcoelho** [comment]
I published a working in progress PR that creates an Ubuntu based image containing a pre compiled libsmartredis.so on /usr/local/lib/ folder.

If possible, I would like help to understand the other requirements:
- What other dependencies should be installed?
- How to build Python clients? I did not find a target on Make for that.

**Comment by Spartee** [comment]
I have reviewed the PR. Thanks for the contribution! ``make lib`` actually builds the Python client too it just doesn't install it. usually we have users run ``pip install .`` or ``pip install -e .`` for editable installs.

Typing this out now I am thinking it might be better to just pip install the Python client directly. (i.e. ``pip install smartredis``), but this wouldn't be good if we wanted to use this image for testing (we would need to build).
