### ISSUE TITLE
Intel Fortran compiler is pinned to older version in CI/CD pipeline

### ISSUE THREAD

**Issue by billschereriii** [CrayLabs/SmartRedis#429]
# Description
The Intel Fortran is pinned to version 2023.2.2 in the CI/CD pipeline because Intel's setup scripts for version 2024.0.0 are not currently working correctly. (Specifically, they're not adding the compiler's location to the system path, so build tools like CMake are unable to find it.) This will undoubtedly be changed in the short term, but this issue will serve as a visible reminder that we need to track this and unpin the compiler once the setup scripts are corrected.

# How to fix
In run_tests.yml and run_static_and_examples.yml, remove "=2023.2.2" from the apt-get of the intel-oneapi-fortran-compiler "Install Intel Compiler" action. If the CI/CD runs to completion for the Intel compiler, the pinning is no longer necessary.

# Expected behavior
CI/CD should be able to be run with the latest version of the compiler.

# System
 - GitHub CI/CD

**Comment by mellis13** [comment]
@billschereriii Can we do a quick if this has been solved.  If not I will file away in OSS backlog

**Comment by billschereriii** [comment]
> @billschereriii Can we do a quick if this has been solved. If not I will file away in OSS backlog

@mellis13 Issue is still present. Rerunning the tests on https://github.com/CrayLabs/SmartRedis/pull/436 shows the issue. I wlll leave it up to simplify retest going forward

**Comment by billschereriii** [comment]
Closing as fixed -- the underlying issue is solved and we no longer pin the compiler version. See PR #436
