### ISSUE TITLE
Branch "f2003" outdated Makefile

### ISSUE THREAD

**Issue by LucasGasparinoBSC** [CrayLabs/SmartRedis#431]
# Description
The Makefile for branch `f2003` on the fork of @ashao uses an outdated Redis++ that is having issues to compile with GCC13. More specifically, GCC 13 requires `cstdint` to be explicitly included, which is not the case for RPP 1.3.5.

# How to reproduce
run `make deps` when GCC13 is the default compiler.

# Expected behavior
Expected `make deps` to succeed.

# System
 - OS: Garuda archlinux
 - OS version: Linux x86 kernel 6.5.9
 - Commit/version of library: @ashao f2003 branch

# Additional info
Simply switching to RPP v1.3.10 worked for me. Requesting fix since this was the recommended branch to use for NVHPC compilers and ensuring library can link against a Fortran code.

**Comment by ashao** [comment]
@LucasGasparinoBSC: Thanks for reaching out and apologies for the delay in reply. I'll get right on this and update this issue when I confirm the fix.

**Comment by ashao** [comment]
Hi @LucasGasparinoBSC, thanks for your patience. To ensure that you could keep up to date with the latest improvements to SmartRedis going forward, we decided to add 'official' support for the NVHPC compiler chain to SmartRedis. Those changes were just incorporated into https://github.com/CrayLabs/SmartRedis/pull/448 which has just been merged into our develop branch. At your convenience, please try out these changes and let us know if this resolves your issues.
