### ISSUE TITLE
ERROR: libsmartredis failed to build and install

### ISSUE THREAD

**Issue by SachinBM-CE** [CrayLabs/SmartRedis#433]
I am trying to execute the following commands to install SmartRedis for my project

```
cd $ROOTDIR
git clone https://github.com/CrayLabs/SmartRedis.git
cd SmartRedis
git checkout v0.2.0
make lib -j
export SMARTREDIS_DIR=$(pwd)
```

But I am getting the following error when `make lib -j` is executed:

```
make[3]: *** [CMakeFiles/smartredisPy.dir/build.make:76: CMakeFiles/smartredisPy.dir/src/python/src/pyclient.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [CMakeFiles/smartredisPy.dir/build.make:328: CMakeFiles/smartredisPy.dir/src/python/bindings/bind.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:156: CMakeFiles/smartredisPy.dir/all] Error 2
make[1]: *** [Makefile:136: all] Error 2
ERROR: libsmartredis failed to build and install
make: *** [Makefile:29: lib] Error 1
```

If more details are necessary please let me know.

**Comment by billschereriii** [comment]
Hi, thanks for reaching out to us!

I would like to start by asking if you are tied to version 0.2 of SmartRedis -- we are currently on version 0.4.2 and expect to release v0.5 shortly. There have been extensive updates to both the libary and the build system since we released v0.2 and both are substantially more robust now.

With that said, if you need to stay with v0.2, I can start with an observation that where build parallelism is supported, we already internally use the -j flag. So rerunning your build without it may make a difference. Also, I notice that you aren't building the dependencies before attempting to build the library. While this step is no longer needed in the current library, with v0.2, you'll have to `make deps` before you can `make lib`.

Please let us know if this helps. If you are still encountering trouble, please let me know the following:

- Platform/OS
- Compiler and version
- Longer tail of the output

Thanks,
Bill

**Comment by SachinBM-CE** [comment]
@billschereriii Thank you for your response.

Yes I am tied to version 0.2 because it is specified by the developers of the end software package I am working with.
I did a `make clean` followed by `make deps` and `make lib` resulting in the same error.

- Platform/OS: x86_64 GNU/Linux (openSUSE Leap 15.4)
- Compiler: gcc-7, g++-7, gfortran-7
- Please find attached the documents with detailed output (make_deps.txt and make_lib.txt).
[make_deps.txt](https://github.com/CrayLabs/SmartRedis/files/13570256/make_deps.txt)
[make_lib.txt](https://github.com/CrayLabs/SmartRedis/files/13570257/make_lib.txt)

Looking forward to your reply. Thanks !!

**Comment by billschereriii** [comment]
Hi,

Thank you for the additional information.

I took a close look at your output files. I have a guess as to what might be causing the problem, but am not 100% sure. We do not regularly test with GCC v7 -- usually we require v8 through v11 (inclusive). I am guessing that the problem you are seeing is (partially) a reflection of a change in the way namespaces were handled between GCC version 7 and GCC version 8.

Specifically, if you look at include/pyclient.h, you'll see that the py namespace is declared inside the SmartRedis namespace, but if you look at include/pydataset.h, you'll see that it is declared outside the SmartRedis namespace. This inconsistency is actually still in the code as of this writing (though I will shortly put in a PR to unify the treatment).

I see three options for you at this point:

1. Speak with the developers of the end software package you am working with to ask them to upgrade to a more current version of SmartRedis. We would be happy to speak with them as well if you are able/willing to share contact information.
2. Upgrade GCC to version 8, 9, or 10. This will match the version we tested with at the time.
3. Failing all else, you could try manually updating pyclient.h in your download to reverse lines 44 and 46 (thereby moving the py namespace declaration outside of the SmartRedis namespace). If you do try this, please let us know if it resolved your problem or if there were additional problems that came about afterwards. We have not tested with GCC v7, so cannot promise that this will help.

I would like to hear how things go for you; please send an update when you get a chance!
Cheers,
Bill

**Comment by SachinBM-CE** [comment]
Hi,

Thank you for your suggestions. I want to go ahead with the 2nd option which is to use version 11 of the gcc compiler.
Currently, I have access to versions 7 and 11. While the version 7 is symbolically linked as follows:
```
/usr/bin/gcc-7 -> gcc
/usr/bin/g++-7 -> g++
/usr/bin/gfortran-7 -> gfortran
```

Now I want to know how to tell `make deps` and `make lib` commands to use gcc-11, g++-11 and gfortran-11 compilers instead of the older version? The upgraded versions are as:
```
/usr/bin/gcc-11
/usr/bin/g++-11
/usr/bin/gfortran-11
```

Should I change `set(CMAKE_C_COMPILER "/usr/bin/cc")` to `set(CMAKE_C_COMPILER "/usr/bin/gcc-11")` in the **CMakeCCompiler.cmake** file?
(or)
Can I set the runtime variable `export CC=/usr/bin/gcc-11` ?

Please let me know about the modifications that are required to use the upgraded versions instead of the older versions. 
Thanks.

**Comment by billschereriii** [comment]
I would go with the `export CC=/usr/bin/gcc-11` approach.
There shouldn't be any other modifications needed to use the more modern compilers.

Cheers,
Bill
