### ISSUE TITLE
python 3.11 support

### ISSUE THREAD

**Issue by laszewsk** [CrayLabs/SmartRedis#447]
# Description
can we have a release for python 3.11?

# Justification
We intend to us smartredis as part of an MLCommons benchmark that also uses tensorflow. Although we can use python3.10, it would be best to support also python.3.11 as tensorflow  and tensorflow-serving is now also for them.

# Implementation Strategy
1. create a while that is supported on python 3.11 with pip install
2. create an Dockerfile example in the source code, so we can add it to docker images we create for the benchmark
4. create a build.def file so we can add it easier to apptainer images we create for the benchmark

My contact: laszewski@gmail.com

**Comment by mellis13** [comment]
Thanks for posting this issue.  We are working on supporting Python 3.11 in the next releases of SmartSim and SmartRedis.  The SmartSim Python 3.11 support can be tracked via https://github.com/CrayLabs/SmartSim/issues/376 .  We will post here when there is a PR available to test with 3.11 support.

**Comment by MattToast** [comment]
Python 3.11 support for SmartRedis has been added to the development branch with the merge of #450! While you _should_ be able to start using it now, we highly recommend using SmartRedis and SmartSim with the same version of Python. SmartSim should also be receiving Python 3.11 shortly with https://github.com/CrayLabs/SmartSim/pull/461.

Both libraries will have official support for Python 3.11 in the next release!
