### ISSUE TITLE
How to connect the ML code (in Python) to the CFD code (in Fortran) using SmartRedis?

### ISSUE THREAD

**Issue by SachinBM-CE** [CrayLabs/SmartRedis#449]
I have an ML code which predicts the wall shear stress. This has to be given as an input to the Fortran code. How can SmartRedis be used in this task? 
Please let me know if further details are required.

**Comment by ashao** [comment]
Hi @SachinBM-CE, thanks for the question. If I could clarify, do you mean that you have a trained ML model (e.g. Torch or Tensorflow)? If so, then there's two steps that you have to do:

1. Instrument the Fortran codebase to initialize the SmartRedis client and provide the appropriate calls. (https://www.craylabs.org/docs/sr_integration.html#full-example)
2. Write a SmartSim driver that will launch both the Redis database and your compiled Fortran application (https://www.craylabs.org/docs/experiment.html)

Please feel free to contact us via Slack if you'd prefer: https://join.slack.com/t/craylabs/shared_invite/zt-nw3ag5z5-5PS4tIXBfufu1bIvvr71UA

**Comment by SachinBM-CE** [comment]
Hi @ashao,
Thank you very much for your response and for the steps to get started.
I am trying to design a "simulation in the loop" setup using Reinforcement Learning (RL) & not a pre-trained ML model.
I would prefer to continue the conversation on Slack & have reached out via Slack for further clarifications.

**Comment by ashao** [comment]
This conversation has moved to Slack. As the work progresses, feel free to post new issues for feature requests and/or to report bugs.
