### ISSUE TITLE
Add gcc-14 support

### ISSUE THREAD

**Issue by mellis13** [CrayLabs/SmartRedis#506]
# Description
Currently only gcc-11 and gcc-12 are tested in the github test suite.  We should add gcc > 12 for users that want to compile with the newest versions of gcc.

# Implementation Strategy
Enabling gcc-14 in the github runner workflows requires moving Ubuntu from 22 to 24.  This has some domino effects, including nvhpc not installing correctly and some failing tests.  Additionally, RedisAI is not automatically buildable with gcc-14, which means that the tests cannot run.  These issues will need to be worked through.

**Comment by ashao** [comment]
Digging into this, there's two problems:
- On Apple Silicon, libtorch from main site does not have some `arm64` symbols. Building this library from scratch resolves this problem
- On Linux, the RedisAI Tensorflow bakend has an inconsistent function signature (even though the types are effectively the same). Patching this on the fly allows this to compile
