### ISSUE TITLE
SmartRedis Fortran Client Does Not Build with PGI Compilers

### ISSUE THREAD

**Issue by rickybalin** [CrayLabs/SmartRedis#58]
# Description
Building the serial Fortran client example `smartredis_put_get_3D.F90` located in `examples/serial/fortran` with PGI compilers (nvfortran specifically) version 21.3.0 I get the following error message:
```
Scanning dependencies of target smartredis_dataset
[ 10%] Building Fortran object CMakeFiles/smartredis_dataset.dir/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/fortran_c_interop.F90.o
[ 20%] Building Fortran object CMakeFiles/smartredis_dataset.dir/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90.o
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
  0 inform,   0 warnings,   1 severes, 0 fatal for get_meta_scalars_i32
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
  0 inform,   0 warnings,   2 severes, 0 fatal for get_meta_scalars_i64
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
  0 inform,   0 warnings,   3 severes, 0 fatal for get_meta_scalars_float
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
  0 inform,   0 warnings,   4 severes, 0 fatal for get_meta_scalars_double
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
  0 inform,   0 warnings,   4 severes, 0 fatal for add_meta_scalar_i32
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
  0 inform,   0 warnings,   4 severes, 0 fatal for add_meta_scalar_i64
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
  0 inform,   0 warnings,   4 severes, 0 fatal for add_meta_scalar_float
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
  0 inform,   0 warnings,   4 severes, 0 fatal for add_meta_scalar_double
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
NVFORTRAN-S-0155-IGNORE_TKR may not be specified for meta (/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90)
  0 inform,   0 warnings,   4 severes, 0 fatal for add_meta_string
CMakeFiles/smartredis_dataset.dir/build.make:107: recipe for target 'CMakeFiles/smartredis_dataset.dir/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90.o' failed
make[2]: *** [CMakeFiles/smartredis_dataset.dir/projects/cfdml_aesp/ML/smartredis-0.1.1/src/fortran/dataset.F90.o] Error 2
CMakeFiles/Makefile2:96: recipe for target 'CMakeFiles/smartredis_dataset.dir/all' failed
make[1]: *** [CMakeFiles/smartredis_dataset.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2
```
Please note that the specific branch of SmartRedis was cloned with the following command `git clone https://github.com/CrayLabs/SmartRedis.git --depth=1 --branch v0.1.1 smartredis-0.1.1`. The `CMakeLists.txt` file was used to build the example code, with the only modification being that `CMAKE_FC_COMPILER` is set to the desired nvfortran compiler path.

# How to reproduce
The error is produced on the ThetaGPU machine at ALCF. From a clean environment obtained executing `module purge`, CMake version 3.19.5 and the NVIDIA HPC SDK version 21.3 are loaded. The `CmakeLists.txt` file available in the example directory  (ensuring nvfortran is used) is then used to configure and build the `smartredis_put_get_3D.F90` example code, producing the compiler error pasted above. No PrgEnv is loaded since none is available on ThetaGPU.

# Expected behavior
The expected behavior is for the Fortran client to build correctly. 

# System
 - OS: Ubuntu 18.04.5 LTS
 - Commit/version of library: I am using the following SmartRedis commit 95ca568474db37d8a027b1def7e87672a592416b

**Comment by Spartee** [comment]
Thanks @rickybalin. We are looking into this. As stated, we haven't specifically used the Nvidia Fortran compiler before, but we have compiled with PGI I believe. I will post here as soon as we know more.

**Comment by Spartee** [comment]
I was able to reproduce the error.

As for using the Nvidia toolchain: 
- It seems as though some of our dependencies (Redis++ and Hiredis) also utilize GNU specific flags which is the first problem. 
- we don't regularly test on the nvidia compilers so users should expect some turbulence when trying to use them

For the GNU MPI issue
 - The base GNU on theta-gpu doesn't have `gfortran` so we need to use the GNU 10 toolchain on theta-gpu. however, this toolchain was installed through spack and the openMPI built on theta-gpu seems to not be compatible. 
 - we get the following error when we try this ``[OMPI users] Fatal Error: Cannot read module file 'mpi.mod' opened at (1), because it was created by a different version of GNU Fortran ``

So next things to try:
 1. use the mpicc mpixx and mpifort for the compilation of all deps and the application
 2. if that doesn't work, try a separate install of either gfortran for GNU 7 or openmpi for GNU 10.

When @mellis13 is back, he will likely take over this investigation.

**Comment by ashao** [comment]
I was playing around with this and compiling the Fortran client directly (it technically doesn't need any dependencies) on my own Ubuntu machine with nvfortran 21.3.0. I'm actually thinking this might be a compiler bug. That seems like a little bit of a copout, but there's two reasons why it might be the case:
- If I comment out all the routines except for the `get_meta_scalars` and `add_meta_scalar` the code compiles just fine
- We never use the `IGNORE_TKR` directive (which I'm pretty sure neither the Intel or GNU compilers support)

I'll spend a little more time in the coming days trying to see if we can work around this (and before pointing fingers too much). It could very well be that there's a coding mistake in one of the other routines that's causing the compiler to signal (incorrectly) in these routines.

**Comment by longb** [comment]
IGNORE_TKR was an invention of the Cray compiler that predated the TYPE(*),DIMENSION(..) declaration in (what is now) standard Fortran.  The sources should probably be "modernized".  (Although nvfortran 21.3 falls pretty far short of conforming to the published Fortran standard.)

**Comment by ashao** [comment]
NVIDIA relatively recently announced that their F18 implementation was accepted by LLVM. There's no date that I could find when it would make it into NVHPC SDK, but the chatter on the forums indicates that they will in the future.
