### ISSUE TITLE
Copy, delete, rename for Python client

### ISSUE THREAD

**Issue by mellis13** [CrayLabs/SmartRedis#62]
# Description
Currently the ``copy``, ``delete``, and ``rename`` operations for tensors and ``DataSet`` are not implemented in the Python client.  These need to be implemented.

# Justification
This is a requested feature in the Python client.

# Implementation Strategy
These functions will follow the same behavior as the C++, C, and Fortran clients.

**Comment by Spartee** [comment]
This is now implemented in #66
