### ISSUE TITLE
Question about running example

### ISSUE THREAD

**Issue by gmuxu** [CrayLabs/SmartRedis#68]
I follow the instruction here: https://www.craylabs.org/docs/installation.html#smartredis to install SmartRedis. I think all of libs are successfully built. And then I compile the examples and no errors. However, when I run smartredis/examples/serial/cpp/build/smartredis_mnist, I get the error as below:

terminate called after throwing an instance of 'std::runtime_error'
  what():  The environment variable SSDB must be set to use the client.
Aborted (core dumped)

Do I miss something when I install smartredis?

**Comment by mellis13** [comment]
Hello,

``SSDB`` is an environment variable used by SmartRedis clients (C/Fortran/C++/Python) to indicate the location of the Redis database or Redis database cluster.

To set the location of the database, run the following command in your terminal (setting the appropriate address and port) before execution of the program:

```bash
export SSDB="address:port"
```

For clusters, you can specify all of the cluster nodes with:

```bash
export SSDB="address_1:port_1,address_2:port_2,address_3:port_3"
```

The Python client has a constructor option that will let you specify the database location, and this will override the need for ``SSDB``.

Let me know if this doesn't work or if you have any other questions.

**Comment by Spartee** [comment]
@gmuxu Just wanted to follow up and see if you were able to run the tests/examples as @mellis13 explained.

**Comment by Spartee** [comment]
Closing this as no response has been given. @gmuxu Please feel free to comment and we will open back up if you still have issues!

**Comment by gmuxu** [comment]
Sorry for the late. Thank you for your help. It works! I am working on running the test case on the cluster recently. If I have further questions, I will let you know. Thank you for the help again.
